Syndicate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static
from shop import views as v

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^constructor/', include('constructor.urls')),
    #url(r'^shop/constructor', v.ConstructorView.as_view(), name = "constructor")

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

constructor/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'constructor'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^constructor/$',views.Constructor.as_view(), name = 'constructor'),

    url(r'^builder/$',views.Builder.as_view(), name = 'builder'),
    url(r'^report/$', views.Report.as_view(), name = 'report'),
    url(r'^report/(?P<pk>[0-9]+)/$',views.Generator.as_view(), name = 'generator'),

    url (r'^report/3d/(?P<pk>[0-9]+)/$', views.DetailDocument.as_view(), name ='document'),
]



forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # /shop/
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
    # /shop/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "detail"),
    # /shop/theme/add/*
    url(r'theme/add/$', views.ThemeCreate.as_view(), name = 'theme-add'),

    url(r'^logout/$', views.Log_out.as_view(), name = 'logout'),

    url(r'^login/$', views.Log_in.as_view(), name='login'),

    url(r'^profile/', views.ProfileDetailView.as_view(),name = 'profile')



]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # /shop/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "product_detail"),




]

forum/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Theme(models.Model):
    creator = models.CharField(max_length = 250)
    theme_title = models.CharField(max_length = 1000)
    theme_def = models.CharField(max_length=1000)
    theme_image = models.CharField(max_length = 2000)
    def __str__(self):
        return self.creator + " - " +self.theme_title

    def get_absolute_url(self):
        return reverse('forum:detail', kwargs={'pk':self.pk})

class Message(models.Model):
    theme  = models.ForeignKey(Theme, on_delete=models.CASCADE)
    author = models.CharField(max_length = 250)
    message_text = models.CharField(max_length = 2000)
    answer_to = models.CharField(max_length = 250)
    #is_fav = models.NullBooleanField()
    def __str__(self):
        return self.author + " : " +self.message_text


forum/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Message

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control"}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))
    class Meta:
        model = User
        fields =  ['username', 'email','password']

class LoginUserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': "form-control"}))

class SendMessageForm(forms.ModelForm):
    message_text = forms.CharField(widget=forms.Textarea(attrs={'class': "form-control"}))
    class Meta:
        model = Message
        fields = ['message_text']



forum/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from .models import Theme, Message
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm, LoginUserForm, SendMessageForm
from django.contrib.auth import logout
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = 'forum/index.html'
    context_object_name = 'themes'

    def get_queryset(self):
        return Theme.objects.all()


class DetailView(generic.DetailView):
    model = Theme
    template_name = 'forum/theme_detail.html'
    form_class = SendMessageForm



    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        form = self.form_class(None)
        context['form'] = form
        return context

    #def get(self, request):

       # return render(request, self.template_name, {'form':form})

    def post(self,request,pk):
        form = self.form_class(request.POST)
        message = Message()
        theme = Theme()
        if form.is_valid():

            message.theme = Theme.objects.get(pk = pk)
            message.author = request.user
            message.message_text = form.cleaned_data['message_text']
            #message.is_fav = True
            message.save()
            return redirect('forum:detail',pk)

class ThemeCreate(CreateView):
    model = Theme
    fields =['creator', 'theme_title', 'theme_image', 'theme_def']

class UserFormView(View):
    form_class = UserForm
    template_name = 'forum/registration_form.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    #process from data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return User objects if credentials(полномочия) are correct
            user = authenticate(username = username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('main:index')

        return render(request, self.template_name, {'form': form})

class Log_out(View):
    def get(self, request):
        logout(request)
        return redirect('main:index')

class Log_in(View):
    form_class = LoginUserForm
    template_name = 'forum/login_form.html'
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self,request):
        form = self.form_class(request.POST)
            # normalized data
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']


            #return User objects if credentials(полномочия) are correct
            user = authenticate(username = username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('main:index')
        messages.error(request,'Пароль неверный или такого пользователя не существует...')
        return render(request, self.template_name, {'form': form})


class ProfileDetailView(View):
    template_name = 'forum/profile.html'

    def get(self,request):
        return render(request,self.template_name,None)



forum/templates/forum/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Syndicate{% endblock %}</title>
    {% load staticfiles %}
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    --><link rel="stylesheet" type = "text/css" href="{% static 'forum/style.css' %}">
    <link rel="stylesheet" type = "text/css" href="{%static 'forum/font-awesome-4.7.0/css/font-awesome.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet" type = text/css>
    {% block heading %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{%url 'main:index'%}">SYNDIC WORKSHOP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" style="">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <a class=" nav-link " href="{% url 'shop:index'%}">
            <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'forum:index'%}"><i class="fa fa-comments" aria-hidden="true"></i></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'constructor:index'%}"><i class="fa fa-cubes" aria-hidden="true"></i></a>
      </li>

    </ul>


      {%if user.is_authenticated%}
      <ul class="navbar-nav">
          <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class = "proflink">{{user.username|upper}}</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'forum:profile'%}">Профиль</a>
            {% if request.user.is_superuser %}

             <a class="dropdown-item" href="{% url 'constructor:report'%}">Список заказов</a>

            {% endif %}
          <a class="dropdown-item" href="{% url 'forum:logout'%}">Выйти</a>

        </div>
      </li>
    </ul>
    {% else %}
        <a class="navbar-brand" href="{%url 'forum:login'%}">Войти</a>
    {%endif%}
  </div>
</nav>

{% block content %}
{%endblock%}

<div class="footer-bottom">
    <div class ="container">
        <div class ="row align-items-center justify-content-center">
            <div class = "col-xs-12">
                <p>Лёня Поддержка 2018
                <a  href="https://t-do.ru/Kohtla"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                <a  href="https://www.instagram.com/jarve_kohtla/"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a  href="https://twitter.com/JarveKohtla"><i class="fa fa-twitter" aria-hidden="true"></i></a>

            </div>
        </div>
    </div>
</div>


<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
</body>
</html>

forum/templates/forum/form_template.html

{%for field in form%}

    <div class="form-group">
      <label>{{field.label_tag}}</label>
      {{field}}
      {{ field.errors }}
    </div>

{% endfor %}

forum/templates/forum/index.html
{% extends 'forum/base.html' %}

{% block title %}Forum{% endblock %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-3">Syndic workshop forum</h1>
  <p class="lead">Это форум мастерской Syndic workshop. Здесь вы можете просмотреть отзывы и задать интересующие вас вопросы!</p>
  <hr class="my-4">
  <p>Написать или прочитать отзывы? А может у вас возникли вопросы? Вам сюда!</p>
  <p class="lead">
      {% for theme in themes%}
            <a class="btn btn-primary btn-lg" href="{% url 'forum:detail' theme.id %}" role="button">{{ theme.theme_title }}</a>
      {% endfor %}
            <a class="btn btn-primary btn-link btn-lg" href="{% url 'forum:theme-add'%}" role="button">Создать</a>
  </p>
</div>


{% endblock %}

forum/templates/forum/login_form.html
{% extends 'forum/base.html'%}
{% block content%}
<div class="container">
    <br>
    {% if messages %}
                <div class="alert alert-dismissible alert-danger">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h4 class="alert-heading">Внимание!</h4>
                  {% for message in messages %}
                    {{ message }}
                    {% endfor %}


                </div>{% endif %}
    <br>

    <div class = "row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 card">
            <div class ="card-body">





    <h2>Авторизация</h2>


    <form  action ="" method = "post" enctype="multipart/form-data">
    <fieldset>
    <legend>Введите ваши данные</legend>
        {% csrf_token %}
        {% include 'forum/form_template.html'%}
                <button type = "submit" class ="btn btn-success">Войти</button>
        <a class ="btn btn-link" href="{% url 'forum:register' %}">Регистрация</a>
    </fieldset>

    </form>

            </div>
        </div>
    </div>


</div>



{% endblock %}

forum/templates/forum/profile.html
{% extends 'forum/base.html' %}

{% block title %}Forum{% endblock %}

{% block content %}


<div class = "container">
    <h2>Личный кабинет</h2>
<div class = "row">
            <div class = "col-md-3">
                <div class="card mb-3">
                  <h3 class="card-header">{{user.username}}</h3>
                  <div class="card-body">

                  </div>
                  <img style="height: 100%; width: 100%; align: center; display: block;" src="https://openclipart.org/download/247319/abstract-user-flat-3.svg" alt="Card image">
                  <div class="card-body">
                    <p class="card-text">E-mail: {{user.email}}</p>
                      <p class="card-text">Имя: {{user.first_name}}</p>
                      <p class="card-text">Фамилия: {{user.last_name}}</p>
                  </div>
                  <div class="card-footer text-muted">

                        Создал свою запись {{user.date_joined}}
                  </div>
                </div>



            </div>
    <div class="col-md-9">
        <h4>Пока заказов нет...</h4>
    </div>
</div>
</div>
{% endblock %}

forum/templates/forum/registration_form.html
{% extends 'forum/base.html'%}
{% block content%}
<div class="container">
    <br>
    <br>
    <div class = "row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4 card">
            <div class ="card-body">
    <h2>Регистрация</h2>


    <form  action ="" method = "post" enctype="multipart/form-data">
    <fieldset>
    <legend>Введите ваши данные</legend>
        {% csrf_token %}
        {% include 'forum/form_template.html'%}
                <button type = "submit" class ="btn btn-success">Сохранить</button>
    </fieldset>
    </form>
            </div>
        </div>
    </div>


</div>



{% endblock %}

forum/templates/forum/theme_detail.html
{% extends 'forum/base.html' %}

{% block title %}{{theme.theme_title}}{% endblock %}

{% block content %}

    <div class="container">
        <h1>Syndic workshop forum</h1>
        <div class ="row">
            <div class = "col-md-3">
                <div class="card mb-3">
                  <h3 class="card-header">{{theme.theme_title}}</h3>
                  <div class="card-body">

                  </div>
                  <img style="height: 100%; width: 100%; display: block;" src="{{theme.theme_image}}" alt="Card image">
                  <div class="card-body">
                    <p class="card-text">{{theme.theme_def}}</p>
                  </div>
                  <div class="card-footer text-muted">
                    created by {{theme.creator}}

                  </div>
                </div>
            </div>
            <div class = "col-md-9">
                <h3>Сообщения</h3>
                {% if error_message %}
                <p><strong>{{error_message}}</strong></p>
                {%endif%}
                {% for message in theme.message_set.all%}
                    <div class="card">
                      <div class="card-body">
                        <h4 class="card-title">{{message.author}}</h4>
                          {% if message.answer_to != "none"%}
                            <h6 class="card-subtitle mb-2 text-muted">{{message.answer_to}}</h6>
                          {% endif %}
                        <p class="card-text">{{message.message_text}}</p>
                      </div>
                    </div>
                <br>
                {% endfor %}
<br>
                <div class="card">
                      <div class="card-body">
                        <form  action ="" method = "post" enctype="multipart/form-data">
                            <fieldset>
                            <legend>Ваше сообщение</legend>
                                {% csrf_token %}
                                {% include 'forum/form_template.html'%}



                                        <button type = "submit" class ="btn btn-success">Отправить</button>
                            </fieldset>
                            </form>
                      </div>
                    </div>
<br>


            </div>
        </div>
    </div>

{% endblock %}

forum/templates/forum/theme_form.html
{% extends 'forum/base.html'%}
{% block content%}
<div class="container">
    <div class = "row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
    <h2>Создание темы</h2>


    <form  action ="" method = "post" enctype="multipart/form-data">
    <fieldset>
    <legend>Введите данные</legend>
        {% csrf_token %}
        {% include 'forum/form_template.html'%}
                <button type = "submit" class ="btn btn-success">Добавить</button>
    </fieldset>
    </form>
        </div>
    </div>


</div>



{% endblock %}