Syndicate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static
from shop import views as v

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^constructor/', include('constructor.urls')),
    #url(r'^shop/constructor', v.ConstructorView.as_view(), name = "constructor")

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

constructor/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'constructor'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    url(r'^constructor/$',views.Constructor.as_view(), name = 'constructor'),

    url(r'^builder/$',views.Builder.as_view(), name = 'builder'),
    url(r'^report/$', views.Report.as_view(), name = 'report'),
    url(r'^report/(?P<pk>[0-9]+)/$',views.Generator.as_view(), name = 'generator'),

    url (r'^report/3d/(?P<pk>[0-9]+)/$', views.DetailDocument.as_view(), name ='document'),
]



forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # /shop/
    url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
    # /shop/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "detail"),
    # /shop/theme/add/*
    url(r'theme/add/$', views.ThemeCreate.as_view(), name = 'theme-add'),

    url(r'^logout/$', views.Log_out.as_view(), name = 'logout'),

    url(r'^login/$', views.Log_in.as_view(), name='login'),

    url(r'^profile/', views.ProfileDetailView.as_view(),name = 'profile')



]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
]

constructor/models.py
from django.db import models
from django.contrib.auth.models import User

class Constructed(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    chest = models.FloatField()
    height = models.FloatField()
    neck = models.FloatField()
    sleeves = models.FloatField()
    shoulder = models.FloatField()
    blueprint = models.FileField(null=True, blank=True)


class Part(models.Model):
    name = models.CharField(max_length = 200)
    def __str__(self):
        return self.name


class PartsInPlace(models.Model):
    part = models.ForeignKey(Part, on_delete=models.CASCADE)
    constructed = models.ForeignKey(Constructed, on_delete=models.CASCADE)
    x = models.FloatField()
    y = models.FloatField()
    z = models.FloatField()
    s = models.FloatField()
    qx = models.FloatField()
    qy = models.FloatField()
    qz = models.FloatField()
    qw = models.FloatField()


constructor/views.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.views.generic import View, ListView, DetailView
from django.shortcuts import render
import json
from constructor.models import Constructed, Part, PartsInPlace
from draw import draw


class IndexView(View):
    template_name = 'constructor/index.html'

    # display blank form
    def get(self, request):
        return render(request, self.template_name, None)

    # process from data
    #def post(self, request):

class Constructor(View):
    template_name = 'constructor/Syndicate.html'
    def get(self, request):
        return render(request, self.template_name, None)

    #def post(self,request):
        #somedata = request.POST['sometext']
        #return render_to_response


class Builder(View):
    template_name = 'constructor/Syndicate.html'
    def get(self, request):
        return render(request, self.template_name, None)


    def post(self,request):
        c = {}
        #c.update(csrf(request))
        print("Сюда все таки обратилось")
        #data = serializers.serialize('json',)
        #print(json.loads(request.body.decode('utf-8')))
        data_unicode = request.body.decode('utf-8')
        #print(data_unicode)
        data = json.loads(request.body)
        #print(data)

        chest = data['chest']
        height = data['height']
        neck = data['neck']
        sleeve = data['sleeve']
        shoulder= data['shoulder']

        print(chest, height, neck, sleeve, shoulder)
        product = Constructed()
        product.user = request.user
        product.chest = chest
        product.height = height
        product.neck = neck
        product.sleeves = sleeve
        product.shoulder = shoulder



        blueprint = draw(int(chest),int(height),int(neck),int(sleeve),int(shoulder))

        product.save()

        image_field = product.blueprint
        img_name = 'my_image.png'
        image_field.save(img_name, InMemoryUploadedFile(blueprint,None,img_name,'image/png', blueprint.tell,None))

        for d in data['details']:
            naming = d['name']
            if(naming!='Main' and naming!='Plane'):
                detail = PartsInPlace()
                detail.part = Part.objects.get(name = naming)
                detail.constructed = product
                tsr = json.loads(d['tsr'])
                #print(tsr['0'])
                detail.x = tsr['0']
                detail.y = tsr['1']
                detail.z = tsr['2']
                detail.s = tsr['3']
                detail.qx = tsr['4']
                detail.qy = tsr['5']
                detail.qz = tsr['6']
                detail.qw = tsr['7']
                detail.save()
                print(detail.part, detail.constructed)
        return render(request, self.template_name, c)




class Report(ListView):
    template_name = "constructor/report.html"
    context_object_name = 'cons'



    def get_queryset(self):
        return Constructed.objects.all().order_by("-created_date")


class Generator(DetailView):
    model = Constructed
    template_name = "constructor/generator.html"

class DetailDocument(DetailView):
    model = Constructed
    template_name = "constructor/document.html"
    return PartsInPlace.objects.filter()



constructor/templates/constructor/Syndicate.html
{% extends 'forum/base.html' %} {% block title %}Конструктор{% endblock %} {% block heading %}

<head>
	<title>Syndicate constructor</title>
	<meta charset="utf-8"> {% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'constructor/Syndicate.min.css' %}">
	<script type="text/javascript" src="{% static 'constructor/b4w.simple.min.js' %}"></script>
</head>
{% endblock %} {% block content %}
<div id="controls-container">
	<!--div class="button-container">
			<div class="delete-container button data-button">
				<div id="delete"></div>
			</div>
			<div id="load-1" class="button data-button"></div>
			<div id="load-2" class="button data-button"></div>
			<div id="ready" class="button data-button"></div>
		</div-->
</div>
<br>
<div class="container">
	<div class="row">
		<div class="col-5 ">

			<div class="card bg-light on-front">
				<div class="card-header">Параметры</div>

				<div class="card-body">
					<div id="cardbox">
					</div>
					<div>
						<form id="post_info">
							<button id="delete" type="button" class="btn btn-outline-danger btn-sm ">Удалить деталь</button>
							<div class="btn-group" role="group">
								<button id="btnGroupDrop2" type="button" class="btn btn-outline-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Добавить деталь</button>
								<div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
									<a class="dropdown-item" id="load-1" href="#">КАРМАН</a>
									<a class="dropdown-item" id="load-2" href="#">ПУГОВКА</a>
								</div>

							</div>
							<!--button id="load-1" type="button" class="btn btn-outline-info btn-block">Карман</button>
					<button id="load-2" type="button" class="btn btn-outline-info btn-block">Пуговка</button-->

							{% csrf_token %}
							<button id="ready" type="submit" class="btn btn-outline-success btn-sm">Готово</button>
						</form>


						<!--button id="ready" type="button" class="btn btn-outline-success">Готово</button-->
					</div>
					<div id="cardbox2">
					</div>
				</div>
			</div>

		</div>
		<div class="col-7">






		</div>
	</div>
</div>
<div id="main_canvas_container"></div>

<script>
	b4w.register("Syndicate_main", function(B, b) {



		function C(a, e) {
			e ? q.load("{% static 'constructor/assets/Syndicate.json' %}", D, null) : console.log("b4w init failure")
		}

		function D(a) {
			E();
			F();
			p.enable_camera_controls();
			console.log("Камера включена");
			//a = document.createElement("div");
			//a.className = "main_sliders_container";
			//a.setAttribute("id", "main_sliders_container");
			//var cardbox = document.getElementById("cardbox");
			//cardbox.appendChild(a);

			g("chest_id", "Обхват груди", 60, 150);
			g("height_id", "Высота изделия", 40, 150);
			g("neck_id", "Обхват шеи", 20, 50);
			g("sleeves_id", "Длина рукава", 5, 100);
			g("shoulder_id", "Пройма", 15, 80);
			create_rotator("rotator", "Поворот детали", 0, 360);
			create_sizer("obj_size", "Размер детали", 0, 5);
		}

		function x(a) {
			a = h.get_all_objects("ALL", a);
			for (var e = 0; e < a.length; e++) {
				var c = a[e];
				if (u.has_physics(c)) {
					u.enable_simulation(c);
					var f = k.create_collision_sensor(c, "Details"),
						d = k.create_selection_sensor(c, !0);
					c == r && k.set_custom_sensor(d, 1);
					k.create_sensor_manifold(c, "COLLISION", k.CT_CONTINUOUS, [f, d], G,
						H);
					(f = v.get_parent(c)) && v.is_armature(f) ? m.set_translation_v(f, y) : m.set_translation_v(c, y)
				}
				v.is_mesh(c) && h.show_object(c)
			}
		}

		function G(a) {
			return a[1]
		}

		function H(a, e, c) {
			1 == c && (k.get_sensor_value(a, e, 0) ? h.set_outline_color(I) : h.set_outline_color(J))
		}

		function F() {
			document.getElementById("controls-container").style.display = "block";
			K();
			console.log("Init_controls");
			document.getElementById("load-1").addEventListener("click", function(a) {
				q.load("{% static 'constructor/assets/Pocket.json' %}", x, null, null, !0)
			});
			document.getElementById("load-2").addEventListener("click",
				function(a) {
					q.load("{% static 'constructor/assets/Button.json' %}", x, null, null, !0)
				});

			$("#post_info").on('submit', function(e) {
				e.preventDefault();

				console.log("Function works")

				a = h.get_all_objects("MESH");
				for (var e, c, f = [], d = 0; d < a.length; d++) e = h.get_object_name(a[d]), c = m.get_tsr(a[d]), c = JSON.stringify(c), f.push({
					name: e,
					tsr: c
				});
				/*console.log(JSON.stringify({
					chest: "50",
					height: "10",
					neck: "1",
					sleeve: "2",
					shoulder: "3",
					details: f
				}));*/
				save_answer_link = "{% url 'constructor:builder' %}";

				function getCookie(name) {
					var cookieValue = null;
					if (document.cookie && document.cookie !== '') {
						var cookies = document.cookie.split(';');
						for (var i = 0; i < cookies.length; i++) {
							var cookie = jQuery.trim(cookies[i]);
							// Does this cookie string begin with the name we want?
							if (cookie.substring(0, name.length + 1) === (name + '=')) {
								cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
								break;
							}
						}
					}
					return cookieValue;
				}
				var csrftoken = getCookie('csrftoken');

				function csrfSafeMethod(method) {
					// these HTTP methods do not require CSRF protection
					return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
				}
				/*$.ajaxSetup({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
							xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					}
				});*/

				var chest = document.getElementById("chest_id").textContent;
				var neck = document.getElementById("neck_id").textContent;
				var height = document.getElementById("height_id").textContent;
				var sleeves = document.getElementById("sleeves_id").textContent;
				var shoulder = document.getElementById("shoulder_id").textContent;



				console.log(chest, neck, height, sleeves, shoulder);


				$.ajax({
					beforeSend: function(xhr, settings) {
						if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
							xhr.setRequestHeader("X-CSRFToken", csrftoken);
						}
					},
					type: 'POST',
					url: save_answer_link,
					data: JSON.stringify({
						chest: chest,
						height: height,
						neck: neck,
						sleeve: sleeves,
						shoulder: shoulder,
						details: f //список с деталями
					}),

					contentType: "application/json; charset=utf-8",
					dataType: "json",
					success: function() {
						console.log("Работает");
					},
					error: function() {
						console.log("Не работает");
					}




				});

			});

			document.getElementById("delete").addEventListener("click", function(a) {
				r && (a = h.get_object_data_id(r), q.unload(a), r = null)
			})
		}

		function K() {
			for (var a = ["delete"], e = 0; e < a.length; e++) {
				var c = a[e];
				document.getElementById(c).addEventListener("mousedown", function(a) {
					a.target.parentNode.classList.add("active")
				});
				document.getElementById(c).addEventListener("mouseup", function(a) {
					a.target.parentNode.classList.remove("active")
				});
				document.getElementById(c).addEventListener("touchstart", function(a) {
					a.target.parentNode.classList.add("active")
				});
				document.getElementById(c).addEventListener("touchend", function(a) {
					a.target.parentNode.classList.remove("active")
				})
			}
		}



		function E() {
			var a = new Float32Array(3),
				e = w.create_pline(),
				c = new Float32Array(3),
				f = l.create(),
				d = l.create(),
				b = z.create(),
				k = function(a, c, e, h, g, k) {
					l.set_trans(g, f);
					z.rotationTo(L.AXIS_Z, k, b);
					m.set_rotation_v(n, b);
					l.set_quat(b, f);
					e && M.is_animated(e) && (m.get_tsr(e, d), l.invert(d, d), l.multiply(d, f, f), a = l.get_trans_view(f), c = l.get_quat_view(f), N.append_stiff(n, e, a, c));
					m.set_tsr(n, f)
				},
				g = O.get_container();


			g.addEventListener("mousedown", function(a) {
				n = h.pick_object(a.clientX, a.clientY);

				if (r != n) {
					if (r)
						h.clear_outline_anim(r);
					if (n)
						h.apply_outline_anim(n, 1, 1, 0);
				}

				r = n;
				if (r) {
					p.disable_camera_controls();
					var sizer = document.getElementById("obj_size_input");
					var sizer_text = document.getElementById("obj_size");

					var size = m.get_scale(r).toFixed(2);



					sizer.value = size;
					sizer_text.textContent = size;
				}




				//p.disable_camera_controls();



			}, !1);
			g.addEventListener("mouseup", function(a) {
				n = null
				p.enable_camera_controls();
				//console.log("Камера включена");
			}, !1);
			g.addEventListener("mousemove", function(b) {
				if (n) {
					var d = b.clientX;
					b = b.clientY;
					p.enable_camera_controls();

					P.calc_ray(h.get_active_camera(), d, b, e);
					w.get_pline_directional_vec(e, c);
					Q.scale(c, 100, c);
					d = h.get_active_camera();
					u.append_ray_test_ext(d, a, c, "ANY", k, !0, !1, !0, !0)
				}
			}, !1)
		}

		function g(a, rus_name, b, c) {
			function e(a) {
				g.textContent = d.value
			}
			var d = R(a, rus_name),
				g = document.getElementById(a);
			d.min = b;
			d.max = c;
			d.step = 1;
			d.value = b;
			g.textContent = d.value;
			!window.ActiveXObject &&
				"ActiveXObject" in window ? d.onchange = e : d.oninput = e
		}



		function create_rotator(a, rus_name, b, c) {
			
			function e(a) {				
				g.textContent = d.value;
				
				
				var rad = d.value - angle;
				console.log(rad);
				rad = L.deg_to_rad(rad);
				//console.log(rad);
				m.rotate_z_local(r,rad);
				angle = d.value;
			
			}
			var d = init_rot_size(a, rus_name),
				g = document.getElementById(a);
			d.min = b;
			d.max = c;
			d.step = 1;
			d.value = b;
			g.textContent = d.value;
			!window.ActiveXObject &&
				"ActiveXObject" in window ? d.onchange = e : d.oninput = e
		}

		function create_sizer(a, rus_name, b, c) {
			function e(a) {
				g.textContent = d.value;
				var sc = d.value;
				console.log(sc);
				m.set_scale(r,sc);

			}
			var d = init_rot_size(a, rus_name),
				g = document.getElementById(a);
			d.min = b;
			d.max = c;
			d.step = 0.1;
			d.value = b;
			g.textContent = d.value;
			!window.ActiveXObject &&
				"ActiveXObject" in window ? d.onchange = e : d.oninput = e
		}

		function init_rot_size(a, rus_name) {
			var b = document.createElement("div");
			b.className = "slider_container";
			var c = document.createElement("div");
			c.className = "text_label";
			var span = document.createElement("span");
			//c.className = "text_label";
			span.textContent = rus_name;
			span.className = "";
			c.appendChild(span);
			var f = document.createElement("input");
			f.className = "input_slider";
			f.setAttribute("id", a + "_input");
			f.setAttribute("type", "range");
			var d = document.createElement("label");
			//d.className = "value_label";
			d.setAttribute("id", a);
			b.appendChild(c);
			b.appendChild(f);
			b.appendChild(d);
			document.getElementById("cardbox2").appendChild(b);
			return f
		}

		function R(a, rus_name) {
			var b = document.createElement("div");
			b.className = "slider_container";
			var c = document.createElement("div");
			c.className = "text_label";
			var span = document.createElement("span");
			//c.className = "text_label";
			span.textContent = rus_name;
			span.className = "";
			c.appendChild(span);
			var f = document.createElement("input");
			f.className = "input_slider";
			f.setAttribute("type", "range");
			var d = document.createElement("label");
			//d.className = "value_label";
			d.setAttribute("id", a);
			b.appendChild(c);
			b.appendChild(f);
			b.appendChild(d);
			document.getElementById("cardbox").appendChild(b);
			return f
		}
		var M = b("animation"),
			N = b("constraints"),
			z = b("quat"),
			Q = b("vec3"),
			P = b("camera"),
			k = b("controls"),
			w = b("math"),
			v = b("objects"),
			u = b("physics"),
			S = b("version"),
			p = b("app"),
			T = b("config"),
			q = b("data");
		b("preloader");
		b("version");
		b("mouse");
		var h = b("scenes"),
			m = b("transform"),
			O = b("container"),
			l = b("tsr"),
			L = b("util");
		b("geometry");
		var angle = 0;
		var r = null,
			J = [0, 1, 0],
			I = [1, 0, 0];
		new Float32Array(2);
		var y = new Float32Array(3);
		new Float32Array(3);
		new Float32Array(3);
		new Float32Array(3);
		new Float32Array(4);
		T.set("physics_uranium_path", "{% static 'constructor/uranium/' %}");
		w.create_pline();
		var n =
			null,
			A = "DEBUG" === S.type(),
			t = T.get_assets_path("Syndicate");
		B.init = function() {
			p.init({
				autoresize: !0,
				callback: C,
				canvas_container_id: "main_canvas_container",
				physics_enabled: !0,
				show_fps: !0,
				assets_dds_available: !A,
				assets_min50_available: !A,
				console_verbose: !0
			})
		}
	});
	b4w.require("Syndicate_main").init();

</script>

{% endblock %}

constructor/templates/constructor/constructor.html
{% extends 'forum/base.html' %}

{% block title %}Syndic shop{% endblock %}

{% block content %}



<h1>Constructor</h1>




{% endblock %}

constructor/templates/constructor/generator.html
{% extends 'forum/base.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}

<div class = "container">
    <h1>Предварительный просмотр</h1>
    <div class ="row">
        <div class ="col-4">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Параметры</h4>

                  <table class="table table-hover">
                      <tbody>

                         <tr>
                          <th scope="row">Обхват груди </th>
                          <td>{{constructed.chest}} см</td>
                         </tr>
                                               <tr>
                          <tr>
                          <th scope="row">Высота изделия </th>
                          <td>{{constructed.height}} см</td>
                         </tr>
                                               <tr>
                          <tr>
                          <th scope="row">Обхват шеи </th>
                          <td>{{constructed.neck}} см</td>
                         </tr>
                                               <tr>
                          <tr>
                          <th scope="row">Длина рукава </th>
                          <td>{{constructed.sleeves}} см</td>
                         </tr>
                                               <tr>
                          <tr>
                          <th scope="row">Пройма </th>
                          <td>{{constructed.shoulder}} см</td>
                         </tr>
                      </tbody>
                  </table>

              </div>
            </div>





        </div>
        <div class ="col-8">
            <div class="card mb-3">
  <h3 class="card-header">Выкройка</h3>

  <img style="height: 100%px; width: 100%; display: block;" src="{{constructed.blueprint.url}}" alt="Card image">

  <div class="card-body">
    <a href="{{constructed.blueprint.url}}" class="card-link">Скачать</a>

  </div>
  <div class="card-footer text-muted">
    {{con.created_date|date:"d/m/Y" }}
  </div>
</div>


        </div>
    </div>

</div>




{% endblock %}

constructor/templates/constructor/index.html
{% extends 'forum/base.html' %}

{% block title %}Конструктор{% endblock %}

{% block content %}

<div class="jumbotron">
  <h3 class="display-4">Главная страница конструктора</h3>

    <h3 class="display-5">Конструирование фасона и формирование выкройки</h3>

  <hr class="my-4">
    {%if user.is_authenticated%}
    <h3 class="display-5">Здравствуйте, {{user.username}}!</h3>
    <p>Здесь начинается ваше творчество!</p>
      <a class="btn btn-primary btn-lg" href="{% url 'constructor:builder'%}" role="button">Начать конструирование</a>
      <a class="btn btn-primary btn-lg" href="#" role="button">Мои работы</a>
    {% else %}
    <p>Для работы вам нужно авторизоваться!</p>
    <a class="btn btn-primary btn-lg" href="{%url 'forum:login'%}" role="button">Войти в систему</a>
    {%endif%}

  <p class="lead">





  </p>
</div>





{% endblock %}

constructor/templates/constructor/report.html
{% extends 'forum/base.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}

<div class = "container">
    <h1>Заказы</h1>
    <div class ="row">

    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Пользователь</th>
      <th scope="col">Дата заказа</th>
      <th scope="col">Расположение объектов</th>
      <th scope="col">Выкройка</th>
    </tr>
  </thead>
  <tbody>
  {% for con in cons%}
     <tr>
      <th scope="row">{{con.user.username}}</th>
      <td>{{con.created_date|date:"d/m/Y" }} {{ con.created_date|time:"H:i"}}</td>
      <td><a class="btn btn-primary btn-sm" href="#" role="button">Просмотреть</a></td>
      <td><a class="btn btn-primary btn-sm" href="{% url 'constructor:generator' con.id%}" role="button">Скачать</a></td>
     </tr>
  {% endfor %}


  </tbody>
</table>


    </div>

</div>




{% endblock %}