Syndicate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from django.conf import settings
from django.conf.urls.static import static
from shop import views as v

urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^constructor/', include('constructor.urls')),
    #url(r'^shop/constructor', v.ConstructorView.as_view(), name = "constructor")

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    # /shop/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # /shop/3
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = "product_detail"),




]

shop/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Material(models.Model):
    name = models.CharField(max_length=50)
    definition = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class Size(models.Model):
    size = models.CharField(max_length=20)
    def __str__(self):
        return self.size

class Colour(models.Model):
    name = models.CharField(max_length=50)
    definition = models.CharField(max_length=500)
    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=50)
    definition = models.CharField(max_length=500)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    definition = models.CharField(max_length = 2000)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    colour = models.ForeignKey(Colour, on_delete=models.CASCADE)
    image = models.CharField(max_length = 1000)
    def __str__(self):
        return self.name + " - "+str(self.price)

class Bucket(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)


class Order(models.Model):
    Bucket = models.ForeignKey(Bucket,on_delete=models.CASCADE)
    completed = models.BooleanField()
    paid = models.BooleanField()
    value = models.FloatField()


class Detail(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    bucket = models.ForeignKey(Bucket, on_delete=models.CASCADE)






shop/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Product
from .serializers import ProductSerializer
from django.views import generic
from django.views.generic import View


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'shop/index.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.all()

class DetailView(generic.DetailView):
    model = Product
    template_name = 'shop/product_detail.html'


shop/templates/shop/index.html
{% extends 'forum/base.html' %}

{% block title %}Syndic shop{% endblock %}

{% block content %}



<div class = "container">
      <h1>Syndic shop</h1>
        <div class = "row">
      {% for product in products %}

            <div class = "col-lg-3">
                <div class="card mb-3">
                  <h3 class="card-header">{{product.name}}</h3>
                  <img style="height: 200px; width: 100%; display: block;" src="{{ product.image}}" alt="Card image">
                    <div class="card-body">
                    <h5 class="card-title">{{product.price}} руб.</h5>
                        <p class ="card-text">{{product.definition}}</p>
                  </div>
                  <div class="card-body">
                      <a href="{% url 'shop:product_detail' product.id%}" class="card-link btn btn-info"><i class="fa fa-info-circle"></i></a>
                      <a href="#" class="card-link btn btn-primary"><i class="fa fa-cart-plus"></i></a>
                  </div>
                </div>
            </div>

        {% if forloop.counter|divisibleby:4 %}
        </div>
        <div class = "row">
        {% endif %}

            <!--a class="" href="#" role="button">{{ product.name }}</a-->
      {% endfor %}
            </div>
</div>




{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'forum/base.html' %}

{% block title %}{{product.name}}{% endblock %}

{% block content %}



<div class = "row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="card mb-3">
  <h3 class="card-header">{{product.name}}</h3>
  <div class="card-body">
    <h5 class="card-title">{{product.price}} руб.</h5>
    <h6 class="card-subtitle text-muted">{{product.category}}</h6>
  </div>
          <div class ="card_image">
               <img style="height: 40%; width: 40%;display: block; margin: 0 auto" src="{{product.image}}" align ="center" alt="Card image">
          </div>
  <div class="card-body">
    <p class="card-text">{{product.definition}}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Материал - {{product.material}}</li>
    <li class="list-group-item">Размер - {{product.size}}</li>
    <li class="list-group-item">Цвет - {{product.colour}}</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Добавить в корзину</a>
    <a href="{% url 'shop:index'%}" class="card-link">Назад</a>
  </div>
  <div class="card-footer text-muted">
    {{product.name}}
  </div>
</div>

    </div>
</div>>


{% endblock %}